# Generated by Django 2.1.3 on 2019-03-27 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='published_words',
            field=models.CharField(max_length=299),
        ),
    ]
