# Generated by Django 2.1.3 on 2019-03-27 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0006_auto_20190324_1611'),
        ('users', '0002_auto_20190327_1331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='published_words',
        ),
        migrations.AddField(
            model_name='profile',
            name='published_words',
            field=models.ManyToManyField(to='words.Word'),
        ),
    ]
