# Generated by Django 2.1.3 on 2019-03-21 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='downvotes',
            new_name='num_vote_down',
        ),
        migrations.RenameField(
            model_name='word',
            old_name='upvotes',
            new_name='num_vote_up',
        ),
    ]
