# Generated by Django 2.1.3 on 2018-11-25 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='word_example',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
