# Generated by Django 2.1.3 on 2018-12-27 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='is_main_field',
            field=models.BooleanField(default=False),
        ),
    ]
