# Generated by Django 2.1.3 on 2018-12-23 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='word_tag',
        ),
        migrations.AlterField(
            model_name='word',
            name='word_example',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
