# Generated by Django 2.1.3 on 2019-03-24 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0003_word_upvoted_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='upvoted_by',
            field=models.CharField(default=None, max_length=1000, null=True),
        ),
    ]
