# Generated by Django 2.1.3 on 2019-03-24 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0005_auto_20190324_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='upvoted_by',
            field=models.CharField(default='0,', max_length=1000),
        ),
    ]
